id: P000408
initial_creation_type: ocr
created_at: 18/03/2020
last_modified_at: 2021-12-16 15:38:25.239240
source_metadata:
  id: bdr:W1KG17607
  title: ས་སྐྱ་པའི་རྒྱུད་ཀྱི་བཤད་རྒྱུན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    c546bc1f82664744bba1ad542f9dd6b3:
      image_group_id: I1KG17922
      title: Volume 1 of sa skya pa'i rgyud kyi bshad rgyun phyogs bsgrigs/
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
