id: opecha:P000408
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17607
  title: ས་སྐྱ་པའི་རྒྱུད་ཀྱི་བཤད་རྒྱུན་ཕྱོགས་བསྒྲིགས།
  volume:
    c546bc1f82664744bba1ad542f9dd6b3:
      image_group_id: I1KG17922
      title: Volume 1 of sa skya pa'i rgyud kyi bshad rgyun phyogs bsgrigs/
      volume_number: 1
      total_pages: 126
  author: ''
ebook_metadata:
  title: ས་སྐྱ་པའི་རྒྱུད་ཀྱི་བཤད་རྒྱུན་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P000408
  cover: cover.jpg
  layers:
  - pagination
